name: deploy_on_dev

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to main server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ARTST_DEV_APP_HOST }}
          username: ${{ secrets.ARTST_DEV_APP_USERNAME }}
          key: ${{ secrets.ARTST_DEV_SSH_KEY }}
          port: ${{ secrets.ARTST_DEV_SSH_PORT }}
          proxy_host: ${{ secrets.ARTST_DEV_BASTION_HOST }}
          proxy_username: ${{ secrets.ARTST_DEV_BASTION_USERNAME }}
          proxy_key: ${{ secrets.ARTST_DEV_BASTION_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use default &&
            cd ~/src/nest-app/ &&
            git pull &&
            npm install &&
            npm run build &&
            pm2 restart nest-app &&
            echo DEPLOY ON DEV DONE SUCCESSFULLY...
